# ===============================
# SERVER
# ===============================
server.port=${SERVER_PORT:9001}
spring.application.name=vnpost_cdp

# ===============================
# POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://${DB_HOST:172.20.0.70}:${DB_PORT:5432}/${DB_NAME:cdp}
spring.datasource.username=${DB_USERNAME:cdp}
spring.datasource.password=${DB_PASSWORD:cdp}
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/cdp
#spring.datasource.username=postgres
#spring.datasource.password=12345
#spring.datasource.driver-class-name=org.postgresql.Driver
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SQL INIT
# ===============================
spring.sql.init.mode=never
spring.sql.init.encoding=UTF-8

# ===============================
# SPRING SECURITY / JWT
# ===============================
#spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI:}
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK_SET_URI:}

# Custom JWT config
app.security.jwt.client-id=${JWT_CLIENT_ID:vnpost-cdp}
app.security.jwt.authority-prefix=ROLE_
app.security.jwt.scope-prefix=SCOPE_

# ===============================
# KAFKA
# ===============================
#spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:172.23.0.17:9092}
spring.kafka.consumer.group-id=${KAFKA_GROUP_ID:vnpost-cdp-group}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=vn.vnpost.cdp.*
spring.kafka.listener.ack-mode=manual

app.kafka.topic.profile-event=${KAFKA_PROFILE_EVENT_TOPIC:cdp.profile.events}

# ===============================
# APACHE UNOMI 3.0.0
# ===============================
app.unomi.base-url=${UNOMI_BASE_URL:'http://172.23.0.17:8181'}
app.unomi.username=${UNOMI_USERNAME:karaf}
app.unomi.password=${UNOMI_PASSWORD:karaf}
app.unomi.connection-timeout-ms=${UNOMI_CONNECTION_TIMEOUT_MS:5000}
app.unomi.response-timeout-ms=${UNOMI_RESPONSE_TIMEOUT_MS:15000}

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

